--
-- Script was generated by Devart dbForge Studio 2022 for SQL Server, Version 6.4.7.0
-- Product home page: http://www.devart.com/dbforge/sql/studio
-- Script date 23/10/2024 6:38:08 AM
-- Server version: 16.00.1130
--


SET DATEFORMAT ymd
SET ARITHABORT, ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER, ANSI_NULLS, NOCOUNT ON
SET NUMERIC_ROUNDABORT, IMPLICIT_TRANSACTIONS, XACT_ABORT OFF
GO
USE master
GO

IF DB_NAME() <> N'master' SET NOEXEC ON

--
-- Create database [KoiPondConstructionManagement]
--
PRINT (N'Create database [KoiPondConstructionManagement]')
GO


--
-- Alter database
--
PRINT (N'Alter database')
GO
ALTER DATABASE KoiPondConstructionManagement
  SET
    ANSI_NULL_DEFAULT OFF,
    ANSI_NULLS OFF,
    ANSI_PADDING OFF,
    ANSI_WARNINGS OFF,
    ARITHABORT OFF,
    AUTO_CLOSE OFF,
    AUTO_CREATE_STATISTICS ON,
    AUTO_SHRINK OFF,
    AUTO_UPDATE_STATISTICS ON,
    AUTO_UPDATE_STATISTICS_ASYNC OFF,
    COMPATIBILITY_LEVEL = 160,
    CONCAT_NULL_YIELDS_NULL OFF,
    CURSOR_CLOSE_ON_COMMIT OFF,
    CURSOR_DEFAULT GLOBAL,
    DATE_CORRELATION_OPTIMIZATION OFF,
    DB_CHAINING OFF,
    HONOR_BROKER_PRIORITY OFF,
    MULTI_USER,
    NUMERIC_ROUNDABORT OFF,
    PAGE_VERIFY CHECKSUM,
    PARAMETERIZATION SIMPLE,
    QUOTED_IDENTIFIER OFF,
    READ_COMMITTED_SNAPSHOT ON,
    RECOVERY FULL,
    RECURSIVE_TRIGGERS OFF,
    TRANSFORM_NOISE_WORDS = OFF,
    TRUSTWORTHY OFF
    WITH ROLLBACK IMMEDIATE
GO

ALTER DATABASE KoiPondConstructionManagement
  SET ENABLE_BROKER
GO

ALTER DATABASE KoiPondConstructionManagement
  SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE KoiPondConstructionManagement
  SET FILESTREAM (NON_TRANSACTED_ACCESS = OFF)
GO

EXECUTE sp_configure 'show advanced options', 1;
GO
RECONFIGURE;
GO
EXECUTE sp_configure 'nested triggers', 1;
GO
RECONFIGURE;
GO

ALTER DATABASE KoiPondConstructionManagement
  SET QUERY_STORE = ON (
    OPERATION_MODE = READ_WRITE,
    CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30),
    DATA_FLUSH_INTERVAL_SECONDS = 900,
    MAX_STORAGE_SIZE_MB = 1000,
    INTERVAL_LENGTH_MINUTES = 60,
    SIZE_BASED_CLEANUP_MODE = AUTO,
    QUERY_CAPTURE_MODE = AUTO,
    MAX_PLANS_PER_QUERY = 200
)
GO

USE KoiPondConstructionManagement
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

USE KoiPondConstructionManagement
GO

IF DB_NAME() <> N'KoiPondConstructionManagement' SET NOEXEC ON
GO

--
-- Create table [dbo].[Users]
--
PRINT (N'Create table [dbo].[Users]')
GO
CREATE TABLE dbo.Users (
  UserID int IDENTITY,
  FullName nvarchar(100) NULL,
  Email nvarchar(100) NULL,
  PasswordHash nvarchar(255) NULL,
  PhoneNumber nvarchar(15) NULL,
  Address nvarchar(255) NULL,
  RoleID int NULL,
  Avatar nvarchar(2048) NULL,
  CONSTRAINT PK__Users__1788CCAC0619AF3F PRIMARY KEY CLUSTERED (UserID)
)
ON [PRIMARY]
GO

--
-- Create index [IX_Users_RoleID] on table [dbo].[Users]
--
PRINT (N'Create index [IX_Users_RoleID] on table [dbo].[Users]')
GO
CREATE INDEX IX_Users_RoleID
  ON dbo.Users (RoleID)
  ON [PRIMARY]
GO

--
-- Create index [UQ__Users__A9D105349EE3CA92] on table [dbo].[Users]
--
PRINT (N'Create index [UQ__Users__A9D105349EE3CA92] on table [dbo].[Users]')
GO
CREATE UNIQUE INDEX UQ__Users__A9D105349EE3CA92
  ON dbo.Users (Email)
  WHERE ([Email] IS NOT NULL)
  ON [PRIMARY]
GO

--
-- Create table [dbo].[ServiceRequests]
--
PRINT (N'Create table [dbo].[ServiceRequests]')
GO
CREATE TABLE dbo.ServiceRequests (
  ServiceRequestID int IDENTITY,
  CustomerID int NULL,
  ServiceID int NULL,
  Status nvarchar(max) NULL,
  CreatedAt datetime NOT NULL DEFAULT (getdate()),
  UpdatedAt datetime NOT NULL DEFAULT (getdate()),
  CONSTRAINT PK__ServiceR__790F6CAB08527AA3 PRIMARY KEY CLUSTERED (ServiceRequestID)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create index [IX_ServiceRequests_CustomerID] on table [dbo].[ServiceRequests]
--
PRINT (N'Create index [IX_ServiceRequests_CustomerID] on table [dbo].[ServiceRequests]')
GO
CREATE INDEX IX_ServiceRequests_CustomerID
  ON dbo.ServiceRequests (CustomerID)
  ON [PRIMARY]
GO

--
-- Create index [IX_ServiceRequests_ServiceID] on table [dbo].[ServiceRequests]
--
PRINT (N'Create index [IX_ServiceRequests_ServiceID] on table [dbo].[ServiceRequests]')
GO
CREATE INDEX IX_ServiceRequests_ServiceID
  ON dbo.ServiceRequests (ServiceID)
  ON [PRIMARY]
GO

--
-- Create table [dbo].[Roles]
--
PRINT (N'Create table [dbo].[Roles]')
GO
CREATE TABLE dbo.Roles (
  RoleID int IDENTITY,
  RoleName nvarchar(50) NULL,
  CONSTRAINT PK__Roles__8AFACE3AC9B5849C PRIMARY KEY CLUSTERED (RoleID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[Promotions]
--
PRINT (N'Create table [dbo].[Promotions]')
GO
CREATE TABLE dbo.Promotions (
  PromotionID int IDENTITY,
  PromotionName nvarchar(100) NULL,
  Description nvarchar(max) NULL,
  DiscountPercentage decimal(5, 2) NOT NULL,
  StartDate date NOT NULL,
  EndDate date NOT NULL,
  PromotionImage nvarchar(2048) NULL,
  CONSTRAINT PK__Promotio__52C42F2F325EA4D0 PRIMARY KEY CLUSTERED (PromotionID)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create table [dbo].[PaymentPolicies]
--
PRINT (N'Create table [dbo].[PaymentPolicies]')
GO
CREATE TABLE dbo.PaymentPolicies (
  PolicyID int IDENTITY,
  PolicyName nvarchar(100) NULL,
  Description nvarchar(max) NULL,
  IsActive bit NOT NULL,
  CONSTRAINT PK__PaymentP__2E13394406BD6B45 PRIMARY KEY CLUSTERED (PolicyID)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create table [dbo].[MaintenanceServices]
--
PRINT (N'Create table [dbo].[MaintenanceServices]')
GO
CREATE TABLE dbo.MaintenanceServices (
  ServiceID int IDENTITY,
  ServiceName nvarchar(100) NULL,
  Description nvarchar(max) NULL,
  Price decimal(18, 2) NULL,
  ServiceImage nvarchar(2048) NULL,
  [Order] int NOT NULL DEFAULT (0),
  RequireDesign bit NOT NULL DEFAULT (CONVERT([bit],(0))),
  CONSTRAINT PK__Maintena__C51BB0EAF9178D2D PRIMARY KEY CLUSTERED (ServiceID)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create table [dbo].[KoiDesigns]
--
PRINT (N'Create table [dbo].[KoiDesigns]')
GO
CREATE TABLE dbo.KoiDesigns (
  DesignID int IDENTITY,
  DesignName nvarchar(100) NULL,
  Description nvarchar(max) NULL,
  CostEstimate nvarchar(100) NULL,
  DesignImage nvarchar(2048) NULL,
  Status int NULL,
  DesignType int NULL,
  CONSTRAINT PK__KoiDesig__32B8E17F671C8093 PRIMARY KEY CLUSTERED (DesignID)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create table [dbo].[Feedback]
--
PRINT (N'Create table [dbo].[Feedback]')
GO
CREATE TABLE dbo.Feedback (
  FeedbackID int IDENTITY,
  CustomerID int NULL,
  RequestID int NULL,
  ServiceRequestID int NULL,
  Rating int NULL,
  Comment nvarchar(500) NULL,
  CreatedAt datetime NOT NULL DEFAULT (getdate()),
  CONSTRAINT PK__Feedback__6A4BEDF672535547 PRIMARY KEY CLUSTERED (FeedbackID)
)
ON [PRIMARY]
GO

--
-- Create index [IX_Feedback_CustomerID] on table [dbo].[Feedback]
--
PRINT (N'Create index [IX_Feedback_CustomerID] on table [dbo].[Feedback]')
GO
CREATE INDEX IX_Feedback_CustomerID
  ON dbo.Feedback (CustomerID)
  ON [PRIMARY]
GO

--
-- Create index [IX_Feedback_RequestID] on table [dbo].[Feedback]
--
PRINT (N'Create index [IX_Feedback_RequestID] on table [dbo].[Feedback]')
GO
CREATE INDEX IX_Feedback_RequestID
  ON dbo.Feedback (RequestID)
  ON [PRIMARY]
GO

--
-- Create index [IX_Feedback_ServiceRequestID] on table [dbo].[Feedback]
--
PRINT (N'Create index [IX_Feedback_ServiceRequestID] on table [dbo].[Feedback]')
GO
CREATE INDEX IX_Feedback_ServiceRequestID
  ON dbo.Feedback (ServiceRequestID)
  ON [PRIMARY]
GO

--
-- Create table [dbo].[ConstructionRequests]
--
PRINT (N'Create table [dbo].[ConstructionRequests]')
GO
CREATE TABLE dbo.ConstructionRequests (
  RequestID int IDENTITY,
  CustomerID int NULL,
  DesignID int NULL,
  CustomDesignDescription nvarchar(max) NULL,
  Status int NULL,
  CreatedAt datetime NOT NULL DEFAULT (getdate()),
  UpdatedAt datetime NOT NULL DEFAULT (getdate()),
  CostEstimate decimal(18, 2) NULL,
  MaintenanceServiceId int NULL,
  RejectReason nvarchar(max) NULL,
  CONSTRAINT PK__Construc__33A8519A9A183ECA PRIMARY KEY CLUSTERED (RequestID)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create index [IX_ConstructionRequests_CustomerID] on table [dbo].[ConstructionRequests]
--
PRINT (N'Create index [IX_ConstructionRequests_CustomerID] on table [dbo].[ConstructionRequests]')
GO
CREATE INDEX IX_ConstructionRequests_CustomerID
  ON dbo.ConstructionRequests (CustomerID)
  ON [PRIMARY]
GO

--
-- Create index [IX_ConstructionRequests_DesignID] on table [dbo].[ConstructionRequests]
--
PRINT (N'Create index [IX_ConstructionRequests_DesignID] on table [dbo].[ConstructionRequests]')
GO
CREATE INDEX IX_ConstructionRequests_DesignID
  ON dbo.ConstructionRequests (DesignID)
  ON [PRIMARY]
GO

--
-- Create index [IX_ConstructionRequests_MaintenanceServiceId] on table [dbo].[ConstructionRequests]
--
PRINT (N'Create index [IX_ConstructionRequests_MaintenanceServiceId] on table [dbo].[ConstructionRequests]')
GO
CREATE INDEX IX_ConstructionRequests_MaintenanceServiceId
  ON dbo.ConstructionRequests (MaintenanceServiceId)
  ON [PRIMARY]
GO

--
-- Create table [dbo].[ConstructionProcess]
--
PRINT (N'Create table [dbo].[ConstructionProcess]')
GO
CREATE TABLE dbo.ConstructionProcess (
  ProcessID int IDENTITY,
  RequestID int NULL,
  Step int NULL,
  Status int NULL,
  AssignedStaffID int NULL,
  CreatedAt datetime NOT NULL DEFAULT (getdate()),
  UpdatedAt datetime NOT NULL DEFAULT (getdate()),
  Note nvarchar(max) NULL,
  StepInfo nvarchar(max) NULL,
  CONSTRAINT PK__Construc__1B39A976DC28FE0E PRIMARY KEY CLUSTERED (ProcessID)
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO

--
-- Create index [IX_ConstructionProcess_AssignedStaffID] on table [dbo].[ConstructionProcess]
--
PRINT (N'Create index [IX_ConstructionProcess_AssignedStaffID] on table [dbo].[ConstructionProcess]')
GO
CREATE INDEX IX_ConstructionProcess_AssignedStaffID
  ON dbo.ConstructionProcess (AssignedStaffID)
  ON [PRIMARY]
GO

--
-- Create index [IX_ConstructionProcess_RequestID] on table [dbo].[ConstructionProcess]
--
PRINT (N'Create index [IX_ConstructionProcess_RequestID] on table [dbo].[ConstructionProcess]')
GO
CREATE INDEX IX_ConstructionProcess_RequestID
  ON dbo.ConstructionProcess (RequestID)
  ON [PRIMARY]
GO

--
-- Create table [dbo].[__EFMigrationsHistory]
--
PRINT (N'Create table [dbo].[__EFMigrationsHistory]')
GO
CREATE TABLE dbo.__EFMigrationsHistory (
  MigrationId nvarchar(150) NOT NULL,
  ProductVersion nvarchar(32) NOT NULL,
  CONSTRAINT PK___EFMigrationsHistory PRIMARY KEY CLUSTERED (MigrationId)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[CustomerOrderHistory]
--
PRINT (N'Create table [dbo].[CustomerOrderHistory]')
GO
CREATE TABLE dbo.CustomerOrderHistory (
  HistoryID int IDENTITY,
  CustomerID int NULL,
  RequestID int NULL,
  CreatedAt datetime NOT NULL DEFAULT (getdate()),
  ActualCost decimal(18, 2) NOT NULL DEFAULT (0.0),
  PaymentMethod int NULL,
  PaymentStatus int NULL,
  CONSTRAINT PK__Customer__4D7B4ADD623FA230 PRIMARY KEY CLUSTERED (HistoryID)
)
ON [PRIMARY]
GO

--
-- Create index [IX_CustomerOrderHistory_CustomerID] on table [dbo].[CustomerOrderHistory]
--
PRINT (N'Create index [IX_CustomerOrderHistory_CustomerID] on table [dbo].[CustomerOrderHistory]')
GO
CREATE INDEX IX_CustomerOrderHistory_CustomerID
  ON dbo.CustomerOrderHistory (CustomerID)
  ON [PRIMARY]
GO

--
-- Create index [IX_CustomerOrderHistory_RequestID] on table [dbo].[CustomerOrderHistory]
--
PRINT (N'Create index [IX_CustomerOrderHistory_RequestID] on table [dbo].[CustomerOrderHistory]')
GO
CREATE INDEX IX_CustomerOrderHistory_RequestID
  ON dbo.CustomerOrderHistory (RequestID)
  ON [PRIMARY]
GO

-- 
-- Dumping data for table __EFMigrationsHistory
--
PRINT (N'Dumping data for table __EFMigrationsHistory')
INSERT dbo.__EFMigrationsHistory VALUES (N'20241010080130_Init', N'8.0.10')
INSERT dbo.__EFMigrationsHistory VALUES (N'20241010082116_InitV2', N'8.0.10')
INSERT dbo.__EFMigrationsHistory VALUES (N'20241010082817_InitV3', N'8.0.10')
INSERT dbo.__EFMigrationsHistory VALUES (N'20241010085802_InitV4', N'8.0.10')
INSERT dbo.__EFMigrationsHistory VALUES (N'20241010090457_InitV5', N'8.0.10')
INSERT dbo.__EFMigrationsHistory VALUES (N'20241010090810_InitV6', N'8.0.10')
INSERT dbo.__EFMigrationsHistory VALUES (N'20241011155639_InitV7', N'8.0.10')
INSERT dbo.__EFMigrationsHistory VALUES (N'20241017153801_InitV8', N'8.0.10')
INSERT dbo.__EFMigrationsHistory VALUES (N'20241017181527_InitV9', N'8.0.10')
INSERT dbo.__EFMigrationsHistory VALUES (N'20241017195110_InitV10', N'8.0.10')
INSERT dbo.__EFMigrationsHistory VALUES (N'20241017201045_InitV11', N'8.0.10')
INSERT dbo.__EFMigrationsHistory VALUES (N'20241018201734_InitV12', N'8.0.10')
INSERT dbo.__EFMigrationsHistory VALUES (N'20241018204534_InitV13', N'8.0.10')
INSERT dbo.__EFMigrationsHistory VALUES (N'20241020070210_InitV14', N'8.0.10')
INSERT dbo.__EFMigrationsHistory VALUES (N'20241021042741_InitV15', N'8.0.10')
GO

-- 
-- Dumping data for table Users
--
PRINT (N'Dumping data for table Users')
SET IDENTITY_INSERT dbo.Users ON
GO
INSERT dbo.Users(UserID, FullName, Email, PasswordHash, PhoneNumber, Address, RoleID, Avatar) VALUES (3, N'Đặng Việt Anh', N'vietdang0407@gmail.com', N'$2a$11$f4FkWPQy.8imwyYsp8g1o.yHNDr5xQgmhDcpV8sZlMPlNBxIn.dOm', N'0355928414', N'Hà Nội', 2, N'images/users/3/avatar/db6c5231-d18b-4521-a9ee-3bbb2768d1f8.ico')
INSERT dbo.Users(UserID, FullName, Email, PasswordHash, PhoneNumber, Address, RoleID, Avatar) VALUES (4, N'Consulting Staff', N'consulting@gmail.com', N'$2a$11$f4FkWPQy.8imwyYsp8g1o.yHNDr5xQgmhDcpV8sZlMPlNBxIn.dOm', N'0368639828', N'Ha Noi', 3, NULL)
INSERT dbo.Users(UserID, FullName, Email, PasswordHash, PhoneNumber, Address, RoleID, Avatar) VALUES (5, N'Design Staff', N'design@gmail.com', N'$2a$11$f4FkWPQy.8imwyYsp8g1o.yHNDr5xQgmhDcpV8sZlMPlNBxIn.dOm', N'0368639828', N'Ha Noi', 4, NULL)
INSERT dbo.Users(UserID, FullName, Email, PasswordHash, PhoneNumber, Address, RoleID, Avatar) VALUES (6, N'Construction staff@gmail.com', N'construction@gmail.com', N'$2a$11$f4FkWPQy.8imwyYsp8g1o.yHNDr5xQgmhDcpV8sZlMPlNBxIn.dOm', N'0368639828', N'Ha Noi', 5, NULL)
INSERT dbo.Users(UserID, FullName, Email, PasswordHash, PhoneNumber, Address, RoleID, Avatar) VALUES (7, N'Manager', N'manager@gmail.com', N'$2a$11$f4FkWPQy.8imwyYsp8g1o.yHNDr5xQgmhDcpV8sZlMPlNBxIn.dOm', N'0368639828', N'Ha Noi', 6, N'images/users/7/avatar/e92c662b-c699-4584-abf4-2896a0b47a4b.jpg')
GO
SET IDENTITY_INSERT dbo.Users OFF
GO

-- 
-- Dumping data for table ServiceRequests
--
PRINT (N'Dumping data for table ServiceRequests')
-- Table KoiPondConstructionManagement.dbo.ServiceRequests does not contain any data (it is empty)

-- 
-- Dumping data for table Roles
--
PRINT (N'Dumping data for table Roles')
SET IDENTITY_INSERT dbo.Roles ON
GO
INSERT dbo.Roles(RoleID, RoleName) VALUES (1, N'Guest')
INSERT dbo.Roles(RoleID, RoleName) VALUES (2, N'Customer')
INSERT dbo.Roles(RoleID, RoleName) VALUES (3, N'Consulting Staff')
INSERT dbo.Roles(RoleID, RoleName) VALUES (4, N'Design Staff')
INSERT dbo.Roles(RoleID, RoleName) VALUES (5, N'Construction Staff')
INSERT dbo.Roles(RoleID, RoleName) VALUES (6, N'Manager')
GO
SET IDENTITY_INSERT dbo.Roles OFF
GO

-- 
-- Dumping data for table Promotions
--
PRINT (N'Dumping data for table Promotions')
-- Table KoiPondConstructionManagement.dbo.Promotions does not contain any data (it is empty)

-- 
-- Dumping data for table PaymentPolicies
--
PRINT (N'Dumping data for table PaymentPolicies')
-- Table KoiPondConstructionManagement.dbo.PaymentPolicies does not contain any data (it is empty)

-- 
-- Dumping data for table MaintenanceServices
--
PRINT (N'Dumping data for table MaintenanceServices')
SET IDENTITY_INSERT dbo.MaintenanceServices ON
GO
INSERT dbo.MaintenanceServices(ServiceID, ServiceName, Description, Price, ServiceImage, [Order], RequireDesign) VALUES (1, N'Dịch vụ vệ sinh', N'<p><strong>Dịch vụ vệ sinh toàn diện hồ cá Koi bao gồm lọc nước, loại bỏ rác thải và làm sạch tảo.</strong></p><ol><li><strong>Cam kết 100% Sạch</strong></li></ol>', 120000.00, N'images/services/b2d22b93-4220-4ee8-bec2-20169d50a3e9.png', 2, CONVERT(bit, 'False'))
INSERT dbo.MaintenanceServices(ServiceID, ServiceName, Description, Price, ServiceImage, [Order], RequireDesign) VALUES (2, N'Kiểm tra chất lượng nước', N'<p>Kiểm tra chất lượng nước để đảm bảo sức khỏe cho cá và duy trì điều kiện sống tốt nhất.</p>', 200000.00, N'images/services/ff19bdcc-d3b4-4f8f-ba3c-31f1b8c48fab.png', 3, CONVERT(bit, 'False'))
INSERT dbo.MaintenanceServices(ServiceID, ServiceName, Description, Price, ServiceImage, [Order], RequireDesign) VALUES (3, N'Bảo dưỡng hồ cá Koi', N'<p>Dịch vụ bảo dưỡng định kỳ bao gồm xử lý nước và kiểm tra thiết bị.</p>', NULL, N'images/services/45823470-e469-47c7-89b1-617ee3fefaae.jpg', 4, CONVERT(bit, 'False'))
INSERT dbo.MaintenanceServices(ServiceID, ServiceName, Description, Price, ServiceImage, [Order], RequireDesign) VALUES (4, N'Loại bỏ tảo', N'<p>Dịch vụ chuyên biệt để loại bỏ tảo phát triển trong hồ cá Koi.</p>', NULL, N'images/services/1180b0e4-aa89-48cb-a8de-5e1bab17b22d.jpg', 5, CONVERT(bit, 'False'))
INSERT dbo.MaintenanceServices(ServiceID, ServiceName, Description, Price, ServiceImage, [Order], RequireDesign) VALUES (5, N'Thay thế bộ lọc', N'<p>Thay thế bộ lọc hồ cá để đảm bảo nước luôn sạch và an toàn cho cá Koi.</p>', NULL, N'images/services/b5ad688a-988d-495c-9c3f-3e9bc68ec708.jpg', 6, CONVERT(bit, 'False'))
INSERT dbo.MaintenanceServices(ServiceID, ServiceName, Description, Price, ServiceImage, [Order], RequireDesign) VALUES (6, N'Thiết kế thi công hồ cá koi', N'<p>Chúng tôi cung cấp dịch vụ toàn diện về lĩnh vực hồ cá koi. Tư vấn khảo sát tại nhà; lên ý tưởng thiết kế, thi công; bàn giao và bảo dưỡng hồ định kỳ.</p>', NULL, N'images/services/f1247c60-dfc2-4c08-bc53-3251384ffbe4.jpg', 1, CONVERT(bit, 'True'))
GO
SET IDENTITY_INSERT dbo.MaintenanceServices OFF
GO

-- 
-- Dumping data for table KoiDesigns
--
PRINT (N'Dumping data for table KoiDesigns')
SET IDENTITY_INSERT dbo.KoiDesigns ON
GO
INSERT dbo.KoiDesigns(DesignID, DesignName, Description, CostEstimate, DesignImage, Status, DesignType) VALUES (1, N'Thiết kế hồ cá koi sân vườn', N'', N'7.100.000 đ/m3 - 9.500.000 đ/m3 ', N'https://kientaocanhquan.vn/uploads/RD4.jpg', NULL, NULL)
GO
SET IDENTITY_INSERT dbo.KoiDesigns OFF
GO

-- 
-- Dumping data for table Feedback
--
PRINT (N'Dumping data for table Feedback')
SET IDENTITY_INSERT dbo.Feedback ON
GO
INSERT dbo.Feedback(FeedbackID, CustomerID, RequestID, ServiceRequestID, Rating, Comment, CreatedAt) VALUES (2, 3, 1, NULL, 5, N'Quá là tốt', '2024-10-23 06:12:42.887')
GO
SET IDENTITY_INSERT dbo.Feedback OFF
GO

-- 
-- Dumping data for table CustomerOrderHistory
--
PRINT (N'Dumping data for table CustomerOrderHistory')
SET IDENTITY_INSERT dbo.CustomerOrderHistory ON
GO
INSERT dbo.CustomerOrderHistory(HistoryID, CustomerID, RequestID, CreatedAt, ActualCost, PaymentMethod, PaymentStatus) VALUES (1, 3, 1, '2024-10-23 05:09:31.587', 30000.00, 1, 2)
GO
SET IDENTITY_INSERT dbo.CustomerOrderHistory OFF
GO

-- 
-- Dumping data for table ConstructionRequests
--
PRINT (N'Dumping data for table ConstructionRequests')
SET IDENTITY_INSERT dbo.ConstructionRequests ON
GO
INSERT dbo.ConstructionRequests(RequestID, CustomerID, DesignID, CustomDesignDescription, Status, CreatedAt, UpdatedAt, CostEstimate, MaintenanceServiceId, RejectReason) VALUES (1, 3, NULL, N'<p>Xin chào bạn tôi muốn yêu cầu bạn làm giúp tôi như sau nhé</p><p>&nbsp;</p>', 4, '2024-10-19 04:13:04.797', '2024-10-20 17:36:28.703', 120000.00, 1, NULL)
GO
SET IDENTITY_INSERT dbo.ConstructionRequests OFF
GO

-- 
-- Dumping data for table ConstructionProcess
--
PRINT (N'Dumping data for table ConstructionProcess')
SET IDENTITY_INSERT dbo.ConstructionProcess ON
GO
INSERT dbo.ConstructionProcess(ProcessID, RequestID, Step, Status, AssignedStaffID, CreatedAt, UpdatedAt, Note, StepInfo) VALUES (1, 1, 1, 0, 6, '2024-10-22 17:02:04.397', '2024-10-23 02:24:12.233', N'<p>Link thiết kế: <a href="https://techhousestore.com.vn/product/iphone-16-pro-max-new-256gb-chinh-hang-vn-a/">https://techhousestore.com.vn/product/iphone-16-pro-max-new-256gb-chinh-hang-vn-a/</a></p>', N'Thi công')
INSERT dbo.ConstructionProcess(ProcessID, RequestID, Step, Status, AssignedStaffID, CreatedAt, UpdatedAt, Note, StepInfo) VALUES (2, 1, 2, 0, 7, '2024-10-22 17:02:08.573', '2024-10-23 02:24:12.233', N'<p>Link thiết kế: <a href="https://techhousestore.com.vn/product/iphone-16-pro-max-new-256gb-chinh-hang-vn-a/">https://techhousestore.com.vn/product/iphone-16-pro-max-new-256gb-chinh-hang-vn-a/</a></p>', N'Nghiệm thu và bàn giao')
GO
SET IDENTITY_INSERT dbo.ConstructionProcess OFF
GO

USE KoiPondConstructionManagement
GO

IF DB_NAME() <> N'KoiPondConstructionManagement' SET NOEXEC ON
GO

--
-- Create foreign key [FK__Users__RoleID__3A81B327] on table [dbo].[Users]
--
PRINT (N'Create foreign key [FK__Users__RoleID__3A81B327] on table [dbo].[Users]')
GO
ALTER TABLE dbo.Users
  ADD CONSTRAINT FK__Users__RoleID__3A81B327 FOREIGN KEY (RoleID) REFERENCES dbo.Roles (RoleID)
GO

--
-- Create foreign key [FK__ServiceRe__Custo__4CA06362] on table [dbo].[ServiceRequests]
--
PRINT (N'Create foreign key [FK__ServiceRe__Custo__4CA06362] on table [dbo].[ServiceRequests]')
GO
ALTER TABLE dbo.ServiceRequests
  ADD CONSTRAINT FK__ServiceRe__Custo__4CA06362 FOREIGN KEY (CustomerID) REFERENCES dbo.Users (UserID)
GO

--
-- Create foreign key [FK__ServiceRe__Servi__4D94879B] on table [dbo].[ServiceRequests]
--
PRINT (N'Create foreign key [FK__ServiceRe__Servi__4D94879B] on table [dbo].[ServiceRequests]')
GO
ALTER TABLE dbo.ServiceRequests
  ADD CONSTRAINT FK__ServiceRe__Servi__4D94879B FOREIGN KEY (ServiceID) REFERENCES dbo.MaintenanceServices (ServiceID)
GO

--
-- Create foreign key [FK__Construct__Custo__3F466844] on table [dbo].[ConstructionRequests]
--
PRINT (N'Create foreign key [FK__Construct__Custo__3F466844] on table [dbo].[ConstructionRequests]')
GO
ALTER TABLE dbo.ConstructionRequests
  ADD CONSTRAINT FK__Construct__Custo__3F466844 FOREIGN KEY (CustomerID) REFERENCES dbo.Users (UserID)
GO

--
-- Create foreign key [FK__Construct__Desig__403A8C7D] on table [dbo].[ConstructionRequests]
--
PRINT (N'Create foreign key [FK__Construct__Desig__403A8C7D] on table [dbo].[ConstructionRequests]')
GO
ALTER TABLE dbo.ConstructionRequests
  ADD CONSTRAINT FK__Construct__Desig__403A8C7D FOREIGN KEY (DesignID) REFERENCES dbo.KoiDesigns (DesignID)
GO

--
-- Create foreign key [FK_ConstructionRequests_MaintenanceServices_MaintenanceServiceId] on table [dbo].[ConstructionRequests]
--
PRINT (N'Create foreign key [FK_ConstructionRequests_MaintenanceServices_MaintenanceServiceId] on table [dbo].[ConstructionRequests]')
GO
ALTER TABLE dbo.ConstructionRequests
  ADD CONSTRAINT FK_ConstructionRequests_MaintenanceServices_MaintenanceServiceId FOREIGN KEY (MaintenanceServiceId) REFERENCES dbo.MaintenanceServices (ServiceID)
GO

--
-- Create foreign key [FK__Feedback__Custom__5441852A] on table [dbo].[Feedback]
--
PRINT (N'Create foreign key [FK__Feedback__Custom__5441852A] on table [dbo].[Feedback]')
GO
ALTER TABLE dbo.Feedback
  ADD CONSTRAINT FK__Feedback__Custom__5441852A FOREIGN KEY (CustomerID) REFERENCES dbo.Users (UserID)
GO

--
-- Create foreign key [FK__Feedback__Reques__5535A963] on table [dbo].[Feedback]
--
PRINT (N'Create foreign key [FK__Feedback__Reques__5535A963] on table [dbo].[Feedback]')
GO
ALTER TABLE dbo.Feedback
  ADD CONSTRAINT FK__Feedback__Reques__5535A963 FOREIGN KEY (RequestID) REFERENCES dbo.ConstructionRequests (RequestID)
GO

--
-- Create foreign key [FK__Feedback__Servic__5629CD9C] on table [dbo].[Feedback]
--
PRINT (N'Create foreign key [FK__Feedback__Servic__5629CD9C] on table [dbo].[Feedback]')
GO
ALTER TABLE dbo.Feedback
  ADD CONSTRAINT FK__Feedback__Servic__5629CD9C FOREIGN KEY (ServiceRequestID) REFERENCES dbo.ServiceRequests (ServiceRequestID)
GO

--
-- Create foreign key [FK__CustomerO__Custo__5CD6CB2B] on table [dbo].[CustomerOrderHistory]
--
PRINT (N'Create foreign key [FK__CustomerO__Custo__5CD6CB2B] on table [dbo].[CustomerOrderHistory]')
GO
ALTER TABLE dbo.CustomerOrderHistory
  ADD CONSTRAINT FK__CustomerO__Custo__5CD6CB2B FOREIGN KEY (CustomerID) REFERENCES dbo.Users (UserID)
GO

--
-- Create foreign key [FK__CustomerO__Reque__5DCAEF64] on table [dbo].[CustomerOrderHistory]
--
PRINT (N'Create foreign key [FK__CustomerO__Reque__5DCAEF64] on table [dbo].[CustomerOrderHistory]')
GO
ALTER TABLE dbo.CustomerOrderHistory
  ADD CONSTRAINT FK__CustomerO__Reque__5DCAEF64 FOREIGN KEY (RequestID) REFERENCES dbo.ConstructionRequests (RequestID)
GO

--
-- Create foreign key [FK__Construct__Assig__45F365D3] on table [dbo].[ConstructionProcess]
--
PRINT (N'Create foreign key [FK__Construct__Assig__45F365D3] on table [dbo].[ConstructionProcess]')
GO
ALTER TABLE dbo.ConstructionProcess
  ADD CONSTRAINT FK__Construct__Assig__45F365D3 FOREIGN KEY (AssignedStaffID) REFERENCES dbo.Users (UserID)
GO

--
-- Create foreign key [FK__Construct__Reque__44FF419A] on table [dbo].[ConstructionProcess]
--
PRINT (N'Create foreign key [FK__Construct__Reque__44FF419A] on table [dbo].[ConstructionProcess]')
GO
ALTER TABLE dbo.ConstructionProcess
  ADD CONSTRAINT FK__Construct__Reque__44FF419A FOREIGN KEY (RequestID) REFERENCES dbo.ConstructionRequests (RequestID)
GO
SET NOEXEC OFF
GO